fix: service Cookie 여부 확인 후 로그아웃
team-aliens/dms-front-admin pull request #118
Opened 2023-03-09 13:43 UTC by jikwan0327

## 특이사항

10분마다 Cookie에 있는 service값 여부 판별 후 true인 경우 로그아웃

## 관련 이슈

- resolved #

2023-03-09 23:07 UTC, jisoung approved these changes

2023-03-19 23:56 UTC, paperdeer commented on src/pages/Root.tsx
> +  }, 600000);
p2)
생각해보니까 이렇게 말고 
`if(!getCookie('service') && (getCookie('access_token') || getCookie('refresh_token'))` 일 때 사용 가능한 서비스 목록을 불러오는 api 호출하는게 나을 것 같아요

2023-03-19 23:56 UTC, paperdeer commented on src/pages/Root.tsx
> +      <Outlet></Outlet>
p4)
self closing 해주세요

2023-03-20 00:22 UTC, jikwan0327 commented on src/pages/Root.tsx
> +  }, 600000);
access토큰과 refresh토큰의 여부를 판단하는 이유가 궁금합니다

2023-03-20 07:33 UTC, paperdeer commented on src/pages/Root.tsx
> +  }, 600000);
토큰이 있는데 로그아웃 시키는건 별로라고 생각해서요

2023-03-27 00:22 UTC, paperdeer approved these changes

2023-03-27 06:09 UTC, JJIIIINN approved these changes

2023-03-27 06:17 UTC, paperdeer requested changes

2023-03-27 06:17 UTC, paperdeer commented on src/pages/Root.tsx
>        removeCookie('service');
p2) 전에 말했던거랑 같은건데 엑세스 토큰 or 리프레시 토큰이 있는데 굳이 로그아웃을 시켜야 할까요?? `사용가능 기능 조회` api를 사용하면 로그아웃 안 시키고도 충분히 네비게이션 바에 기능들이 노출 안 되는걸 막을 수 있을거 같아서요

2023-03-27 06:36 UTC, paperdeer commented on src/pages/Root.tsx
>        removeCookie('service');
그리고 지금 발생하는 문제는 service라는 키값의 쿠키를 저장할 때 expires를 설정 안 해서 그런거 같은데
expires를 10년뒤 이렇게 줘도 해결 가능할거 같아요

2023-03-27 23:57 UTC, paperdeer commented on src/apis/schools/index.ts
> +import { IsUseAbleFeature } from '../auth/response';
궁금했던건데 인터페이스 네이밍 컨벤션이 언제 저렇게 된거죠?

2023-03-27 23:57 UTC, paperdeer commented on src/apis/schools/response.ts
> +
import 지워주세요

2023-03-28 03:31 UTC, jikwan0327 commented on src/pages/Root.tsx
>        removeCookie('service');
쿠키 만료시간을 설정하였는데 현재 년도에서 일정 년도를 더해주니 최대 1년 1개월까지 밖에 추가로 만료시간이 설정되어 일단 최대로 올려두었습니다

2023-03-30 01:40 UTC, paperdeer approved these changes

2023-03-30 04:01 UTC, merged