(#68) 잔류 페이지
team-aliens/dms-front-admin pull request #69
Opened 2023-03-01 14:02 UTC by jisoung

## 특이사항

## 관련 이슈

- resolved #68

2023-03-01 14:49 UTC, jikwan0327 approved these changes

2023-03-02 05:17 UTC, paperdeer requested changes

2023-03-02 05:17 UTC, paperdeer commented on src/apis/remains/index.tsx
> +    });
이거 useMutate 훅으로 빼서 하는게 좋아보여요

2023-03-02 05:17 UTC, paperdeer commented on src/components/apply/remains/deleteModal.tsx
> +  deleteModal: boolean;
```suggestion
  isDeleteModal: boolean;
```
은 어떤가요

2023-03-02 05:17 UTC, paperdeer commented on src/components/apply/remains/remainModal.tsx
> +  );
이거 연관된 값 같은데 객체로 묶고, useForm 사용해주세요

2023-03-02 05:17 UTC, paperdeer commented on src/components/apply/remains/remainModal.tsx
> +  };
이것도 useForm에 있는 함수 사용해주세요

2023-03-02 05:17 UTC, paperdeer commented on src/components/apply/remains/timeModal.tsx
> +};
util 함수로 빼내고, 매개변수 네이밍 text말고, day 같은걸로 수정해주세요.
그리고 타입지정 해주세요

2023-03-02 05:17 UTC, paperdeer commented on src/components/apply/remains/timeModal.tsx
> +};
이것도 유틸함수로 빼주세요

2023-03-02 05:17 UTC, paperdeer commented on src/components/apply/remains/timeModal.tsx
> +  timeModal: boolean;
이것도 isTimeModal 같이 boolean값이라는걸 인지할 수 있는 네이밍을 수정해주세요

2023-03-02 05:17 UTC, paperdeer commented on src/components/apply/remains/timeModal.tsx
> +  const [endMin, setEndMin] = useState(remainTime?.end_time.slice(3, 5));
이것도 객체로 묶어서 useForm 사용해주세요

2023-03-02 05:17 UTC, paperdeer commented on src/components/apply/remains/timeModal.tsx
> +  };
좋은 방법이긴 한데, useFrom으로 묶고 useForm의 onHandleChange 함수를 사용해주세요. Input 컴포넌트에 name 속성주고 e.target.name으로 객체 관리하면 더 예쁠것 같아요

2023-03-02 05:17 UTC, paperdeer commented on src/pages/apply/remains/index.tsx
> +  const [timeModal, setTimeModal] = useState(false);
isRemainModalOpen 같은 네이밍은 어떤가요

2023-03-02 05:17 UTC, paperdeer commented on src/pages/apply/remains/index.tsx
> +  const [selectModalId, setSelectModalId] = useState<string>('');
이거 useModal에 selectedModal이라는 값으로 대체  불가능할까요?

2023-03-02 05:17 UTC, paperdeer commented on src/pages/apply/remains/index.tsx
> +  const [timeModal, setTimeModal] = useState(false);
그리고 추가적으로 모달이 열려있는지 여부를 왜 이렇게 관리하는지 궁금해요

2023-03-02 05:17 UTC, paperdeer commented on src/pages/apply/remains/index.tsx
> +}
이게 뭐죠

2023-03-02 05:17 UTC, paperdeer commented on src/pages/apply/remains/index.tsx
> +              <_CheckInput id="menu" type="checkbox" />
이거 디자인시스템을 사용하지 않은 이유가 있을까요??

2023-03-02 14:00 UTC, merged